# Generated by Django 4.1 on 2022-11-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_user_alter_userprofile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password',
            new_name='username',
        ),
    ]
