# Generated by Django 4.1 on 2022-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caloriegoal',
            field=models.CharField(default='2000', max_length=100),
        ),
    ]
