# Generated by Django 4.1 on 2022-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_caloriegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='caloriegoal',
            field=models.CharField(default='3000', max_length=100),
        ),
    ]
